name: Trigger auto deployment for mednow-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mednow-frontend-AutoDeployTrigger-3bdf7fa5-70bd-4aa6-8adf-3dac2e042cc0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEDNOWFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEDNOWFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEDNOWFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cruujnv4wbww33u.azurecr.io
          registryUsername: ${{ secrets.MEDNOWFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEDNOWFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: mednow-frontend
          resourceGroup: Medic
          imageToBuild: cruujnv4wbww33u.azurecr.io/mednow-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


